name: Publish
on:
  push:
    branches:
      - "main"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install asciidoctor
        run: npm install -g asciidoctor asciidoctor-chunker

      - name: Build
        run: asciidoctor Livro.adoc -o index.html

      # - name: Split
      #   run: asciidoctor-chunker index.html -o output

      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host:     ${{ secrets.PYTHONFLUENTE_HOST }}
          username: ${{ secrets.PYTHONFLUENTE_USER }}
          password: ${{ secrets.PYTHONFLUENTE_PASSWORD }}
          port: 22
          source: "index.html"
          # source: "output/*"
          target: "~/pythonfluente.com/"
